const Sports = [
  {
    id: 1,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "0",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 2,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 3,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 4,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 5,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 6,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 7,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 8,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 9,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 10,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 11,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 12,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 13,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 14,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 15,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 16,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 17,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 18,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://img.freepik.com/free-vector/vintage-chess-competition-poster_1284-40125.jpg?w=2000",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
];

export const MainCampus = [
  {
    id: 1,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 2,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 3,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 4,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 5,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 6,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 7,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 8,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 9,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 10,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 11,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 12,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 13,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 14,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 15,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 16,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 17,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 18,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU9GcR8sQheBeVMwaILPkJCHIin6vbOzvh8ejYOb1I3rlEYAAvqVZfPTiJ5LdMtlAnmPt3fF2Q&usqp=CAU",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
];

export const Trending = [
  {
    id: 1,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 2,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 3,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 4,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 5,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 6,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 7,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 8,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 9,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 10,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 11,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 12,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 13,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 14,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 15,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 16,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 17,
    Name: "MCS Chess Tournament",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 18,
    Name: "MCS Chess Tournament2",
    ImagePath: "https://ieeetv.ieee.org/assets/video-images/large/132229.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
];

export const Seminar = [
  {
    id: 1,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 2,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 3,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 4,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 5,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 6,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 7,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 8,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 9,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 10,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 11,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 12,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 13,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 14,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 15,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 16,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 17,
    Name: "MCS Chess Tournament",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
  {
    id: 18,
    Name: "MCS Chess Tournament2",
    ImagePath:
      "https://images.template.net/17881/Business-Seminar-Poster-Editable-0.jpg",
    Fee: "Free",
    Location: "Jinnah Coy",
    Date: "29-12-2022",
    Registered: "15",
    Totalseats: "25",
  },
];

export default Sports;
